name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Version with GitVersion
        run: |
          dotnet tool install --global GitVersion.Tool -v q
          dotnet-gitversion /updateprojectfiles

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test /p:Configuration=Release --no-build --verbosity normal

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          fail_on_unmatched_files: true
          generate_release_notes: true
          prerelease: ${{ contains( github.ref, '-rc' ) || contains( github.ref, '-beta' ) }}
          files: |
            **/*.nupkg
            LICENSE

      - name: Publish
        run: nuget push **/*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
